### PR TITLE
Add ttl value

### LINKED ISSUE #13: Support a TtlValue
Or does this make sense for a separate crate?

### PR DESCRIPTION
**Pull request by mathstuf**
---
Fixes #13.

### CODE REVIEW

**Comment by stusmall** [comment]
Looks like the CI problem is with the stats feature.  It is a conditional compile that tracks hit/miss count for the cache.

**Comment by mathstuf** [comment]
Fixed. Thanks for the heads up.

**Comment by stusmall** [comment]
Cool.  I'll give this a review tonight.

**Comment by mathstuf** [comment]
Ping? :)

**Comment by mathstuf** [comment]
Ping? :)

**Comment by stusmall** [comment]
Sorry!  This fell off my plate. Last time I made a quick look over it I had a few questions.  I'll give it a close look this weekend and get back to you.

**Comment by stusmall** [comment]
I'm having trouble finding the impact of this.  It looks like it changes the name of the Entry struct and makes it public.  This doesn't seem to change the public signature of the TtlCache itself but just exposes one internal value.  Am I missing something?

**Comment by mathstuf** [comment]
> This doesn't seem to change the public signature of the TtlCache itself but just exposes one internal value. Am I missing something?

Correct.

**Comment by stusmall** [comment]
What do you want to use it for?

**Comment by mathstuf** [comment]
We use it to hold the API token for an installation which has an expiration time.  See [the API docs](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-an-installation). When the token is no longer valid, we know that we need to get a new one.

**Comment by stusmall** [comment]
Would using the a cache with a value of 1 give you the same behavior?  I'm just trying to avoid exposing internal impl unless it's useful in a general case.

**Comment by mathstuf** [comment]
We use it [here](https://gitlab.kitware.com/utils/rust-ghostflow/blob/master/ghostflow-github/src/authorization.rs#L179) for the token and [here](https://gitlab.kitware.com/utils/ghostflow-director/commit/156a648cf69056c5da1e29192bdd46eb77da81f7) to handle refreshing our permission cache (which we only expire as an entire batch operation, not per-user to minimize API queries).

Having to do `ttl_cache.get(()).expect()` would make it mildly more annoying to use the APIs.

**Comment by stusmall** [comment]
That makes sense.  I'm sorry but I think this makes sense in a separate crate.  Sorry it took so long to get to but I appreciate the patience

**Comment by mathstuf** [comment]
Would it make sense to base this crate on that new crate then?

**Pull request closed without merging**
